### ISSUE TITLE
Rate limit wall 

### ISSUE THREAD

**Issue by emilyhobson** [stamen/usopendata#14]
Encourage user login when API rate limit is reached

**Comment by ericsoco** [comment]
Up and running. Looks like this:

![screen shot 2016-09-19 at 9 12 22 pm](https://cloud.githubusercontent.com/assets/1127259/18657333/f342de04-7ead-11e6-932e-042794d0de9b.png)


@waldoj let me know if you want to change copy.

**Comment by waldoj** [comment]
It's fine. :) It's trivial for me to amend that.
