### ISSUE TITLE
Set up GitHub Pages redirect to openredist.org

### ISSUE THREAD

**Issue by ericsoco** [stamen/usopendata#32]

**Comment by waldoj** [comment]
Done. Not sure why I'm getting a GitHub 404, though.

**Comment by ericsoco** [comment]
Because I forgot step 2 (had to enter `openredist.org` in the repo settings).
We're live! (shhh! don't tell anyone.)
http://openredist.org/

**Comment by waldoj** [comment]
I forget that _every_ time. I create a `CNAME` file, point the DNS at GitHub's IPs, and then I'm confused why it doesn't work. I have easily a dozen sites hosted on GitHub Pages, too. :-/

**Comment by ericsoco** [comment]
Actually -- the problem was that I didn't have my `CNAME` in the build folder and so wasn't getting copied over to `gh-pages`. You can enter it manually in Settings, but that gets blown away if you push again to `gh-pages`. I'm guessing that entering it there actually just creates a `CNAME` in the `gh-pages` branch for you.
